=== Internet2/grouper/src/resources/schema/ldappc.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema targetNamespace="http://grouper.internet2.edu/ldappc"
  xmlns="http://www.w3.org/2001/XMLSchema"
  xmlns:beans="http://www.springframework.org/schema/beans"
  xmlns:ldappc="http://grouper.internet2.edu/ldappc"
  xmlns:grouper="http://grouper.internet2.edu/shibboleth/2.0"
  xmlns:resolver="urn:mace:shibboleth:2.0:resolver"
  xmlns:service="urn:mace:shibboleth:2.0:services"
  xmlns:spml="urn:oasis:names:tc:SPML:2:0"
  xmlns:spmldsml="urn:oasis:names:tc:SPML:2:0:DSML"
  elementFormDefault="qualified">

  <import namespace="http://www.springframework.org/schema/beans" />

  <import namespace="urn:mace:shibboleth:2.0:services" schemaLocation="classpath:/schema/shibboleth-2.0-services.xsd" />
  <import namespace="urn:mace:shibboleth:2.0:resolver" schemaLocation="classpath:/schema/shibboleth-2.0-attribute-resolver.xsd" />
  <import namespace="urn:oasis:names:tc:SPML:2:0" schemaLocation="classpath:/schema/pstc_spmlv2_core.xsd" />
  <!-- 
  <import namespace="urn:oasis:names:tc:SPML:2:0:DSML" schemaLocation="classpath:/schema/pstc_spmlv2_dsml.xsd" />
 -->
 
  <annotation>
    <documentation>Experimental Schema for the next version of LDAPPC</documentation>
  </annotation>

  <complexType name="ProvisioningServiceProvider">
    <complexContent>
      <extension base="service:ServiceType">
        <attribute name="authority" type="string" use="required">
          <annotation>
            <documentation>TODO</documentation>
          </annotation>
        </attribute>
      </extension>
    </complexContent>
  </complexType>

  <element name="ldappc" type="ldappc:ldappcType" />
  <complexType name="ldappcType">
    <sequence>
      <element name="targets" type="ldappc:TargetsType" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <element name="targets" type="ldappc:TargetsType" />
  <complexType name="TargetsType">
    <sequence>
      <element name="target" type="ldappc:TargetType" minOccurs="1" maxOccurs="unbounded" />
      <element name="object" type="ldappc:PSOType" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
    <attribute name="id" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="TargetType">
    <!--
      <sequence> <element name="object" type="ldappc:PSOType" minOccurs="1" maxOccurs="unbounded" /> </sequence>
    -->
    <attribute name="id" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="provider" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="ConnectionType">
    <attribute name="id" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="PSOType">
    <sequence>
      <element name="identifier" type="ldappc:PSOIdentifierType" />
      <element name="attribute" type="ldappc:AttributeDefinitionType" minOccurs="0" maxOccurs="unbounded" />
      <element name="references" type="ldappc:ReferencesDefinitionType" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="id" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="authoritative" type="boolean" use="optional" default="false">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>

  </complexType>

  <complexType name="PSOIdentifierType">
    <sequence>
      <element name="identifyingAttribute" type="ldappc:IdentifyingAttributeType" />
    </sequence>
    <attribute name="ref" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="baseId" type="string">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="AttributeDefinitionType">
    <attribute name="name" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="ref" type="string">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="isMultiValued" type="string" default="true">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="ReferencesDefinitionType">
    <sequence>
      <element name="reference" type="ldappc:ReferenceDefinitionType" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
    <attribute name="name" type="string" use="required">
      <annotation>
        <documentation>v</documentation>
      </annotation>
    </attribute>
    <attribute name="emptyValue" type="string">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>

  </complexType>

  <complexType name="ReferenceDefinitionType">
    <attribute name="toObject" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="ref" type="string">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="LdapPoolProvider">
    <complexContent>
      <extension base="service:ServiceType">
        <attribute name="ldapPoolId" type="string" use="required">
          <annotation>
            <documentation>TODO</documentation>
          </annotation>
        </attribute>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="IdentifyingAttributeType">
    <attribute name="name" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="value" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>
  
</schema>

=== Internet2/grouper/src/test/edu/internet2/middleware/ldappc/spml/config/ConfigBeanParserTest.macro.before.xml
<?xml version="1.0" encoding="utf-8"?>

<ldappc xmlns="http://grouper.internet2.edu/ldappc"
        xmlns:ldappc="http://grouper.internet2.edu/ldappc"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://grouper.internet2.edu/ldappc classpath:/schema/ldappc.xsd">

  <targets id="ActiveDirectory">

    <target id="ad-prod" provider="provider-ad-prod" />
    <target id="ad-test" provider="provider-ad-test" />

    <object id="group" authoritative="true">
      <identifier ref="groupDn-${target}" baseId="ou=groups,dc=grouper,dc=edu" />
      <attribute name="objectclass" ref="ad-objectclass" />
      <attribute name="cn" />
      <attribute name="description" />
      <attribute name="hasMember" />
      <references name="member">
        <reference ref="members-jdbc" toObject="member" />
        <reference ref="members-g:gsa" toObject="group" />
      </references>
    </object>

    <object id="member">
      <identifier ref="memberDn-${target}" baseId="ou=people,dc=grouper,dc=edu" />
      <attribute name="isMemberOf" ref="memberIsMemberOf" />
    </object>

  </targets>

  <targets id="OpenLDAP">

    <target id="openldap-prod" provider="provider-openldap-prod" />
    <target id="openldap-test" provider="provider-openldap-test" />

    <object id="group" authoritative="true">
      <identifier ref="groupDn-${target}" baseId="ou=groups,dc=grouper,dc=edu" />
      <attribute name="objectclass" ref="openldap-objectclass" />
      <attribute name="cn" />
      <attribute name="description" />
      <attribute name="hasMember" ref="hasMember" />
      <references name="member">
        <reference ref="members-jdbc" toObject="member" />
        <reference ref="members-g:gsa" toObject="group" />
      </references>
    </object>

    <object id="member">
      <identifier ref="memberDn-${target}" baseId="ou=people,dc=grouper,dc=edu" />
      <attribute name="isMemberOf" ref="memberIsMemberOf" />
      <references name="memberOf">
        <reference ref="memberIsMemberOf" toObject="group" />
      </references>
    </object>

  </targets>
  
</ldappc>

=== Internet2/grouper/src/test/edu/internet2/middleware/ldappc/spml/config/ConfigBeanParserTest.macro.after.xml
<?xml version="1.0" encoding="utf-8"?>

<ldappc xmlns="http://grouper.internet2.edu/ldappc"
        xmlns:ldappc="http://grouper.internet2.edu/ldappc"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://grouper.internet2.edu/ldappc classpath:/schema/ldappc.xsd">

  <targets id="ActiveDirectory">

    <target id="ad-prod" provider="provider-ad-prod">

      <object id="group" authoritative="true" targetId="ad-prod">
        <identifier ref="groupDn-ad-prod" baseId="ou=groups,dc=grouper,dc=edu" />
        <attribute name="objectclass" ref="ad-objectclass" />
        <attribute name="cn" />
        <attribute name="description" />
        <attribute name="hasMember" />
        <references name="member">
          <reference ref="members-jdbc" toObject="member" />
          <reference ref="members-g:gsa" toObject="group" />
        </references>
      </object>

      <object id="member" targetId="ad-prod">
        <identifier ref="memberDn-ad-prod" baseId="ou=people,dc=grouper,dc=edu" />
        <attribute name="isMemberOf" ref="memberIsMemberOf" />
      </object>

    </target>

    <target id="ad-test" provider="provider-ad-test">

      <object id="group" authoritative="true" targetId="ad-test">
        <identifier ref="groupDn-ad-test" baseId="ou=groups,dc=grouper,dc=edu" />
        <attribute name="objectclass" ref="ad-objectclass" />
        <attribute name="cn" />
        <attribute name="description" />
        <attribute name="hasMember" />
        <references name="member">
          <reference ref="members-jdbc" toObject="member" />
          <reference ref="members-g:gsa" toObject="group" />
        </references>
      </object>

      <object id="member" targetId="ad-test">
        <identifier ref="memberDn-ad-test" baseId="ou=people,dc=grouper,dc=edu" />
        <attribute name="isMemberOf" ref="memberIsMemberOf" />
      </object>

    </target>

  </targets>

  <targets id="OpenLDAP">

    <target id="openldap-prod" provider="provider-openldap-prod">


      <object id="group" authoritative="true" targetId="openldap-prod">
        <identifier ref="groupDn-openldap-prod" baseId="ou=groups,dc=grouper,dc=edu" />
        <attribute name="objectclass" ref="openldap-objectclass" />
        <attribute name="cn" />
        <attribute name="description" />
        <attribute name="hasMember" ref="hasMember" />
        <references name="member">
          <reference ref="members-jdbc" toObject="member" />
          <reference ref="members-g:gsa" toObject="group" />
        </references>
      </object>

      <object id="member" targetId="openldap-prod">
        <identifier ref="memberDn-openldap-prod" baseId="ou=people,dc=grouper,dc=edu" />
        <attribute name="isMemberOf" ref="memberIsMemberOf" />
        <references name="memberOf">
          <reference ref="memberIsMemberOf" toObject="group" />
        </references>
      </object>

    </target>

    <target id="openldap-test" provider="provider-openldap-test">

      <object id="group" authoritative="true" targetId="openldap-test">
        <identifier ref="groupDn-openldap-test" baseId="ou=groups,dc=grouper,dc=edu" />
        <attribute name="objectclass" ref="openldap-objectclass" />
        <attribute name="cn" />
        <attribute name="description" />
        <attribute name="hasMember" ref="hasMember" />
        <references name="member">
          <reference ref="members-jdbc" toObject="member" />
          <reference ref="members-g:gsa" toObject="group" />
        </references>
      </object>

      <object id="member" targetId="openldap-test">
        <identifier ref="memberDn-openldap-test" baseId="ou=people,dc=grouper,dc=edu" />
        <attribute name="isMemberOf" ref="memberIsMemberOf" />
        <references name="memberOf">
          <reference ref="memberIsMemberOf" toObject="group" />
        </references>
      </object>

    </target>

  </targets>

</ldappc>

=== Internet2/grouper/src/test/edu/internet2/middleware/ldappc/spml/config/ConfigBeanParserTest.xml
<?xml version="1.0" encoding="UTF-8"?><ldappc xmlns="http://grouper.internet2.edu/ldappc" xmlns:ldappc="http://grouper.internet2.edu/ldappc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://grouper.internet2.edu/ldappc classpath:/schema/ldappc.xsd">

  <targets id="ActiveDirectory">

    <target id="ad-prod" provider="provider-ad-prod"/>
    <target id="ad-test" provider="provider-ad-test"/>

    

    

  <object id="group" targetId="ad-prod">
      <identifier id="group-dn" targetId="ad-prod"/>
      <attribute name="objectclass"/>
      <attribute name="cn"/>
      <reference id="members-jdbc" name="member" toPSOId="member"/>
    </object>
      <object id="member" targetId="ad-prod">
      <identifier id="member-dn" targetId="ad-prod"/>
    </object>
      <object id="group" targetId="ad-test">
      <identifier id="group-dn" targetId="ad-test"/>
      <attribute name="objectclass"/>
      <attribute name="cn"/>
      <reference id="members-jdbc" name="member" toPSOId="member"/>
    </object>
      <object id="member" targetId="ad-test">
      <identifier id="member-dn" targetId="ad-test"/>
    </object>
   </targets>

  <targets id="OpenLDAP">

    <target id="openldap-prod" provider="provider-openldap-prod"/>
    <target id="openldap-test" provider="provider-openldap-test"/>

    

    

  <object id="group" targetId="openldap-prod">
      <identifier id="group-dn" targetId="openldap-prod"/>
      <attribute name="objectclass"/>
      <attribute name="cn"/>
      <attribute id="hasMember" name="hasMember"/>
      <reference id="members-jdbc" name="member" toPSOId="member"/>
    </object>
      <object id="member" targetId="openldap-prod">
      <identifier id="member-dn" targetId="openldap-prod"/>
      <attribute id="member-isMemberOf" name="isMemberOf"/>
    </object>
      <object id="group" targetId="openldap-test">
      <identifier id="group-dn" targetId="openldap-test"/>
      <attribute name="objectclass"/>
      <attribute name="cn"/>
      <attribute id="hasMember" name="hasMember"/>
      <reference id="members-jdbc" name="member" toPSOId="member"/>
    </object>
      <object id="member" targetId="openldap-test">
      <identifier id="member-dn" targetId="openldap-test"/>
      <attribute id="member-isMemberOf" name="isMemberOf"/>
    </object>
   </targets>

</ldappc>
