=== Internet2/grouper/ldappcng/ldappcng/src/main/resources/schema/ldappc.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema targetNamespace="http://grouper.internet2.edu/ldappc"
  xmlns="http://www.w3.org/2001/XMLSchema"
  xmlns:beans="http://www.springframework.org/schema/beans"
  xmlns:ldappc="http://grouper.internet2.edu/ldappc"
  xmlns:grouper="http://grouper.internet2.edu/shibboleth/2.0"
  xmlns:resolver="urn:mace:shibboleth:2.0:resolver"
  xmlns:dc="urn:mace:shibboleth:2.0:resolver:dc"
  xmlns:service="urn:mace:shibboleth:2.0:services"
  xmlns:spml="urn:oasis:names:tc:SPML:2:0"
  xmlns:spmldsml="urn:oasis:names:tc:SPML:2:0:DSML"
  elementFormDefault="qualified">

  <import namespace="http://www.springframework.org/schema/beans" />

  <import namespace="urn:mace:shibboleth:2.0:services" schemaLocation="classpath:/schema/shibboleth-2.0-services.xsd" />
  <import namespace="urn:mace:shibboleth:2.0:resolver" schemaLocation="classpath:/schema/shibboleth-2.0-attribute-resolver.xsd" />
  <import namespace="urn:mace:shibboleth:2.0:resolver:dc" schemaLocation="classpath:/schema/shibboleth-2.0-attribute-resolver-dc.xsd" />
  <import namespace="urn:oasis:names:tc:SPML:2:0" schemaLocation="classpath:/schema/pstc_spmlv2_core.xsd" />
  <import namespace="http://grouper.internet2.edu/shibboleth/2.0" schemaLocation="classpath:/schema/shibboleth-2.0-grouper.xsd" />
  <!--
    <import namespace="urn:oasis:names:tc:SPML:2:0:DSML" schemaLocation="classpath:/schema/pstc_spmlv2_dsml.xsd" />
  -->

  <annotation>
    <documentation>Experimental Schema for the next version of LDAPPC</documentation>
  </annotation>

  <complexType name="ProvisioningServiceProvider">
    <complexContent>
      <extension base="service:ServiceType">
        <attribute name="authority" type="string" use="required">
          <annotation>
            <documentation>TODO</documentation>
          </annotation>
        </attribute>
      </extension>
    </complexContent>
  </complexType>

  <element name="ldappc" type="ldappc:ldappcType" />
  <complexType name="ldappcType">
    <sequence>
      <element name="targets" type="ldappc:TargetsType" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <element name="targets" type="ldappc:TargetsType" />
  <complexType name="TargetsType">
    <sequence>
      <element name="target" type="ldappc:TargetType" minOccurs="1" maxOccurs="unbounded" />
      <element name="object" type="ldappc:PSOType" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
    <attribute name="id" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="TargetType">
    <!--
      <sequence> <element name="object" type="ldappc:PSOType" minOccurs="1" maxOccurs="unbounded" /> </sequence>
    -->
    <attribute name="id" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="provider" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="bundleModifications" type="boolean" default="true">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="ConnectionType">
    <attribute name="id" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="PSOType">
    <sequence>
      <element name="identifier" type="ldappc:PSOIdentifierType" />
      <element name="attribute" type="ldappc:AttributeDefinitionType" minOccurs="0" maxOccurs="unbounded" />
      <element name="references" type="ldappc:ReferencesDefinitionType" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="id" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="authoritative" type="boolean" use="optional" default="false">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>

  </complexType>

  <complexType name="PSOIdentifierType">
    <sequence>
      <element name="identifyingAttribute" type="ldappc:IdentifyingAttributeType" />
    </sequence>
    <attribute name="ref" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="baseId" type="string">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="AttributeDefinitionType">
    <attribute name="name" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="ref" type="string">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="isMultiValued" type="string" default="true">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="retainAll" type="boolean" default="false">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="ReferencesDefinitionType">
    <sequence>
      <element name="reference" type="ldappc:ReferenceDefinitionType" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
    <attribute name="name" type="string" use="required">
      <annotation>
        <documentation>v</documentation>
      </annotation>
    </attribute>
    <attribute name="emptyValue" type="string">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>

  <complexType name="ReferenceDefinitionType">
    <attribute name="toObject" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="ref" type="string">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="onNotFound" default="warn">
      <simpleType>
        <restriction base="string">
          <enumeration value="fail" />
          <enumeration value="ignore" />
          <enumeration value="warn" />
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="multipleResults" type="boolean" default="false" />
  </complexType>

  <complexType name="LdapPoolProvider">
    <complexContent>
      <extension base="service:ServiceType">
        <attribute name="ldapPoolId" type="string" use="required">
          <annotation>
            <documentation>TODO</documentation>
          </annotation>
        </attribute>
        <attribute name="logLdif" type="boolean" default="false" />
        <attribute name="logSpml" type="boolean" default="false" />
      </extension>
    </complexContent>
  </complexType>

  <complexType name="IdentifyingAttributeType">
    <attribute name="name" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
    <attribute name="value" type="string" use="required">
      <annotation>
        <documentation>TODO</documentation>
      </annotation>
    </attribute>
  </complexType>
  
   <complexType name="SPMLDataConnector">
    <annotation>
      <documentation>
        A data connector that can returns information from an SPML provider.
      </documentation>
    </annotation>
    <complexContent>
      <extension base="grouper:BaseGrouperDataConnectorType">
        <sequence>
          <element name="FilterTemplate" type="string">
            <annotation>
              <documentation>TODO</documentation>
            </annotation>
          </element>
          <element name="ResultCache" type="dc:CacheConfigType" minOccurs="0" />
        </sequence>
        <attribute name="provider" type="string" use="required" />
        <attribute name="base" type="string" use="required" />
        <attribute name="scope" type="grouper:ScopeType" use="optional" default="subTree" />
        <attribute name="returnData" type="grouper:ReturnDataType" use="optional" default="everything" />
        <attribute name="templateEngine" type="string" fixed="shibboleth.TemplateEngine">
          <annotation>
            <documentation>TODO</documentation>
          </annotation>
        </attribute>
      </extension>
    </complexContent>
  </complexType>
  
  <complexType name="LdapDnPSOIdentifier">
    <complexContent>
      <extension base="resolver:BaseAttributeDefinitionType">
        <attribute name="structure" use="required">
          <annotation>
            <documentation>
              An SPML PSOIdentifier which is an LDAP DN.
            </documentation>
          </annotation>
          <simpleType>
            <restriction base="string">
              <enumeration value="flat" />
              <enumeration value="bushy" />
            </restriction>
          </simpleType>
        </attribute>
        <attribute name="base" type="string" use="required">
          <annotation>
            <documentation>TODO</documentation>
          </annotation>
        </attribute>
        <attribute name="rdnAttributeName" type="string" use="required">
          <annotation>
            <documentation>TODO</documentation>
          </annotation>
        </attribute>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="PSOIdentifier">
    <complexContent>
      <extension base="resolver:BaseAttributeDefinitionType">
      </extension>
    </complexContent>
  </complexType>

</schema>

=== Internet2/grouper/ldappcng/ldappcng/conf/examples/ldappcng-ApacheDS/ldappcng.xml
<?xml version="1.0" encoding="utf-8"?>

<ldappc xmlns="http://grouper.internet2.edu/ldappc"
        xmlns:ldappc="http://grouper.internet2.edu/ldappc"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://grouper.internet2.edu/ldappc classpath:/schema/ldappc.xsd">

  <targets id="LDAP">

    <target id="ldap" provider="ldap-provider" />

    <object id="stem">
      <identifier ref="stem-dn" baseId="${groupsOU}">
        <identifyingAttribute name="objectclass" value="organizationalUnit" />
      </identifier>
      <attribute name="objectClass" ref="stem-objectclass" />
      <attribute name="ou" ref="stem-ou" />
      <attribute name="description" ref="stem-description" />
    </object>

    <object id="group" authoritative="true">
      <identifier ref="group-dn" baseId="${groupsOU}">
        <identifyingAttribute name="objectClass" value="${groupObjectClass}" />
      </identifier>
      <attribute name="objectClass" ref="group-objectclass-eduMember" />
      <attribute name="cn" />
      <attribute name="description" />
      <attribute name="hasMember" ref="hasMember" />
      <attribute name="isMemberOf" ref="groupIsMemberOf" />
      <references name="member" emptyValue="" >
        <reference ref="members-jdbc" toObject="member" />
        <reference ref="members-g:gsa" toObject="group" />
      </references>
    </object>

    <object id="member">
      <identifier ref="member-dn" baseId="${peopleOU}">
        <identifyingAttribute name="objectclass" value="person" />
      </identifier>
      <attribute name="objectClass" ref="member-objectclass" retainAll="true" />
      <attribute name="isMemberOf" ref="memberIsMemberOf" />
    </object>

  </targets>

</ldappc>
